name: CI Python Vulnerable Build

on:
  pull_request_target:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: gh-action-pip-audit
        uses: pypa/gh-action-pip-audit@v1.0.0
        with:
          inputs: requirements.txt

      - name: Secret
        env:
          SECRET_API_KEY: ${{ secrets.API_KEY }}
        run: echo "Secret loaded"

      - name: print artifact
        run: cat artefact_leak.txt
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute command
        run: |
          echo "Running eval simulation..."
          eval "$INPUT_COMMAND"

      - name: Run script
        run: python code_vuln.py

      - name: Print secret
        run: echo "$SECRET_API_KEY"
        
      - name: Upload dummy artifact
        run: echo "Simulation complète"
